### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by rucoder** [lf-edge/eve-rust#1]
I think changing from 1.80.1 to 1.80.2 wen we add more tools is confusing
I would rather do 1.80.1-1 where -1 is our initial version. Rust itself uses the 3rd digit
e.g. https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html
```
What's in 1.80.1

Rust 1.80.1 fixes two regressions that were recently reported
```

**Comment by deitch** [comment]
Exactly what you wrote. If this is `FROM rust:1.80.1-alpine3.19`, then we release `lfedge/eve-rust:1.80.1`. When we bump to `FROM rust:1.80.2`, then we release `lfedge/eve-rust:1.80.2`. We try _really_ hard that if we want to add tools or change things - such that we need a new version of `lfedge/eve-rust`, we sync it up with a new version of rust, however small (major, minor or patch). Only if we _really_ have no choice, and _have_ to cut a new image of `eve-rust`, and there is no way to bump eve version, will we then do `eve-rust:1.80.1-1`. But I expect that pretty much never to happen.

**Comment by rucoder** [comment]
yes, I read it again and realized I misunderstood it. closing now
